/**
 * Canonical CSS custom property names for ArchRecon tokens (Figma-aligned).
 * Use with `var(${ar.color.semantic.textPrimary})` in inline styles or style objects.
 */
export const ar = {
  color: {
    accent: {
      25: "--ar-color-accent-25",
      50: "--ar-color-accent-50",
      100: "--ar-color-accent-100",
      200: "--ar-color-accent-200",
      300: "--ar-color-accent-300",
      400: "--ar-color-accent-400",
      500: "--ar-color-accent-500",
      600: "--ar-color-accent-600",
      700: "--ar-color-accent-700",
    },
    neutral: {
      0: "--ar-color-neutral-0",
      "0-50": "--ar-color-neutral-0-50",
      50: "--ar-color-neutral-50",
      100: "--ar-color-neutral-100",
      200: "--ar-color-neutral-200",
      300: "--ar-color-neutral-300",
      400: "--ar-color-neutral-400",
      500: "--ar-color-neutral-500",
      600: "--ar-color-neutral-600",
      700: "--ar-color-neutral-700",
      800: "--ar-color-neutral-800",
      900: "--ar-color-neutral-900",
      "900-0": "--ar-color-neutral-900-0",
      "900-20": "--ar-color-neutral-900-20",
      "900-50": "--ar-color-neutral-900-50",
    },
    primary: {
      25: "--ar-color-primary-25",
      50: "--ar-color-primary-50",
      75: "--ar-color-primary-75",
      100: "--ar-color-primary-100",
      200: "--ar-color-primary-200",
      300: "--ar-color-primary-300",
      400: "--ar-color-primary-400",
      500: "--ar-color-primary-500",
      600: "--ar-color-primary-600",
      700: "--ar-color-primary-700",
      800: "--ar-color-primary-800",
      900: "--ar-color-primary-900",
    },
    state: {
      error: "--ar-color-state-error",
      warning: "--ar-color-state-warning",
      successBg: "--ar-color-state-success-bg",
      successBoarder: "--ar-color-state-success-boarder",
      successText: "--ar-color-state-success-text",
      inProgressBg: "--ar-color-state-in-progess-bg",
      inProgressBoarder: "--ar-color-state-in-progess-boarder",
      inProgressText: "--ar-color-state-in-progess-text",
      infoBg: "--ar-color-state-info-bg",
      infoBoarder: "--ar-color-state-info-boarder",
      infoText: "--ar-color-state-info-text",
    },
    semantic: {
      background: {
        brand: "--ar-color-semantic-background-brand",
        brandFaint: "--ar-color-semantic-background-brand-faint",
        brandSoft: "--ar-color-semantic-background-brand-soft",
        brandStrong: "--ar-color-semantic-background-brand-strong",
        brandSubtle: "--ar-color-semantic-background-brand-subtle",
        card: "--ar-color-semantic-background-card",
        cardHover: "--ar-color-semantic-background-card-hover",
        cardInverse: "--ar-color-semantic-background-card-inverse",
        default: "--ar-color-semantic-background-default",
        elevated: "--ar-color-semantic-background-elevated",
        inverse: "--ar-color-semantic-background-inverse",
        subtle: "--ar-color-semantic-background-subtle",
      },
      border: {
        default: "--ar-color-semantic-border-default",
        disabled: "--ar-color-semantic-border-disabled",
        error: "--ar-color-semantic-border-error",
        focus: "--ar-color-semantic-border-focus",
        strong: "--ar-color-semantic-border-strong",
        subtle: "--ar-color-semantic-border-subtle",
        success: "--ar-color-semantic-border-success",
      },
      button: {
        disabled: "--ar-color-semantic-button-disabled",
        disabledBoarder: "--ar-color-semantic-button-disabled-boarder",
        disabledText: "--ar-color-semantic-button-disabled-text",
        primary: "--ar-color-semantic-button-primary",
        primaryBoarder: "--ar-color-semantic-button-primary-boarder",
        primaryHover: "--ar-color-semantic-button-primary-hover",
        primaryText: "--ar-color-semantic-button-primary-text",
        primaryTextHover: "--ar-color-semantic-button-primary-text-hover",
        secondary: "--ar-color-semantic-button-secondary",
        secondaryBoarder: "--ar-color-semantic-button-secondary-boarder",
        secondaryHover: "--ar-color-semantic-button-secondary-hover",
        secondaryTexHover: "--ar-color-semantic-button-secondary-tex-hover",
        secondaryText: "--ar-color-semantic-button-secondary-text",
        tertiary: "--ar-color-semantic-button-tertiary",
        tertiaryBoarder: "--ar-color-semantic-button-tertiary-boarder",
        tertiaryHover: "--ar-color-semantic-button-tertiary-hover",
        tertiaryText: "--ar-color-semantic-button-tertiary-text",
        tertiaryTextHover: "--ar-color-semantic-button-tertiary-text-hover",
      },
      icon: {
        hover: "--ar-color-semantic-icon-hover",
        outline: "--ar-color-semantic-icon-outline",
        outlineBoarder: "--ar-color-semantic-icon-outline-boarder",
        outlineHover: "--ar-color-semantic-icon-outline-hover",
        outlineText: "--ar-color-semantic-icon-outline-text",
        primary: "--ar-color-semantic-icon-primary",
        text: "--ar-color-semantic-icon-text",
      },
      state: {
        error: "--ar-color-semantic-state-error",
        inProgress: "--ar-color-semantic-state-in-progress",
        info: "--ar-color-semantic-state-info",
        success: "--ar-color-semantic-state-success",
        warning: "--ar-color-semantic-state-warning",
      },
      text: {
        disabled: "--ar-color-semantic-text-disabled",
        inverse: "--ar-color-semantic-text-inverse",
        link: "--ar-color-semantic-text-link",
        linkHover: "--ar-color-semantic-text-link-hover",
        muted: "--ar-color-semantic-text-muted",
        primary: "--ar-color-semantic-text-primary",
        secondary: "--ar-color-semantic-text-secondary",
      },
    },
  },
  font: {
    family: {
      body: "--ar-font-family-body",
      heading: "--ar-font-family-heading",
      ui: "--ar-font-family-ui",
    },
    size: {
      "3xs": "--ar-font-size-3xs",
      "2xs": "--ar-font-size-2xs",
      xs: "--ar-font-size-xs",
      sm: "--ar-font-size-sm",
      m: "--ar-font-size-m",
      lg: "--ar-font-size-lg",
      xl: "--ar-font-size-xl",
      "2xl": "--ar-font-size-2xl",
      "3xl": "--ar-font-size-3xl",
    },
    weight: {
      light: "--ar-font-weight-weight-light",
      regular: "--ar-font-weight-weight-regular",
      medium: "--ar-font-weight-weight-medium",
      semibold: "--ar-font-weight-weight-semibold",
      bold: "--ar-font-weight-weight-bold",
    },
  },
  letterSpacing: {
    tight: "--ar-letter-spacing-tracking-tight",
    normal: "--ar-letter-spacing-tracking-normal",
    wide: "--ar-letter-spacing-tracking-wide",
  },
  lineHeight: {
    "2xs": "--ar-line-height-2xs",
    xs: "--ar-line-height-xs",
    sm: "--ar-line-height-sm",
    md: "--ar-line-height-md",
    lg: "--ar-line-height-lg",
    xl: "--ar-line-height-xl",
    "2xl": "--ar-line-height-2xl",
    "3xl": "--ar-line-height-3xl",
  },
  opacity: {
    0: "--ar-opacity-0",
    10: "--ar-opacity-10",
    20: "--ar-opacity-20",
    40: "--ar-opacity-40",
    60: "--ar-opacity-60",
    80: "--ar-opacity-80",
    100: "--ar-opacity-100",
  },
  size: {
    1: "--ar-size-1",
    2: "--ar-size-2",
    3: "--ar-size-3",
    4: "--ar-size-4",
    5: "--ar-size-5",
    6: "--ar-size-6",
    containerSm: "--ar-size-container-sm",
    containerMd: "--ar-size-container-md",
    containerLg: "--ar-size-container-lg",
  },
  space: {
    1: "--ar-space-1",
    2: "--ar-space-2",
    3: "--ar-space-3",
    4: "--ar-space-4",
    6: "--ar-space-6",
    8: "--ar-space-8",
    12: "--ar-space-12",
    16: "--ar-space-16",
    20: "--ar-space-20",
    24: "--ar-space-24",
    28: "--ar-space-28",
    32: "--ar-space-32",
    36: "--ar-space-36",
  },
  strokeWeight: {
    thin: "--ar-stroke-weight-thin",
    regular: "--ar-stroke-weight-regular",
    medium: "--ar-stroke-weight-medium",
    thick: "--ar-stroke-weight-thick",
    heavy: "--ar-stroke-weight-heavy",
  },
  legacy: {
    bg: "--ar-bg",
    surface: "--ar-surface",
    text: "--ar-text",
    textMuted: "--ar-text-muted",
    border: "--ar-border",
    primary: "--ar-primary",
    primaryHover: "--ar-primary-hover",
    secondary: "--ar-secondary",
    secondaryHover: "--ar-secondary-hover",
  },
} as const;
